# Generated by Django 3.0.8 on 2020-08-20 04:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0004_auto_20200819_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 4, 4, 30, 190084, tzinfo=utc)),
        ),
    ]
