# Generated by Django 3.0.8 on 2020-08-21 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0006_auto_20200820_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 18, 30, 16, 393117, tzinfo=utc)),
        ),
    ]
